version: '3.1'
services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: pass_db
      POSTGRES_DB: course_db
    ports:
      - 5433:5432
